server:
  port: 8000
spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8080
          predicates:
            - Path=/authenticate,/register
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "OPTIONS"
logging:
  level:
    org.springframework.cloud.gateway.handler.predicate: trace
